baseURL = 'https://ivaaan.neocities.org'
title = 'soko Sijeni'
languageCode = 'es-es'
defaultContentLanguage = 'es'
pluralizelisttitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.sass]
        outputStyle = "compressed"
